Add Redux
mosaicchristian/mosaicapp pull request #1
Opened 2017-05-19 14:02 UTC by BKreisel

Add redux to the project with some basic middleware 🎈

2017-05-19 14:17 UTC, mnmercer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/VhD9WmTW/1-test)

2017-05-22 13:35 UTC, mnmercer requested changes

2017-05-22 13:35 UTC, mnmercer commented on main.js
> +
Why an extra line?

2017-05-22 21:37 UTC, BKreisel commented on main.js
> +
that is a good question. Removed

2017-05-24 13:23 UTC, mnmercer approved these changes

2017-05-24 13:24 UTC, merged